-- =============================================================================
-- FVMLTD Farmer Crop Assistant — schema reference
-- =============================================================================
-- Source of truth: supabase/migrations/*.sql
--
-- Canonical production tables:
--   farmer_profiles, farms, crop_checks, crop_photos, chat_messages,
--   assessment_results, staff_profiles
--
-- Application extensions (created by the baseline migration when missing):
--   crop_cycles, soil_tests, follow_ups, lab_test_requests, products,
--   recommendations
--
-- Conversational agronomy memory (additive; does not replace crop_checks):
--   agronomy_cases, agronomy_case_messages, agronomy_case_outcomes,
--   agronomy_case_reviews
--
-- Regional agri-input + weather risk tables (additive Caribbean catalogue):
--   countries, agri_inputs, input_registrations, input_crop_uses,
--   supplier_inventory, input_sources, input_verification_history,
--   weather_locations, weather_snapshots, disease_risk_models,
--   disease_risk_rules, disease_risk_assessments, farmer_risk_alerts
--
-- Do NOT create parallel tables such as farmers / crop_cases / case_photos /
-- ai_assessments / case_messages / staff_users.
--
-- Apply migrations in filename order (or `supabase db push`).
-- On an existing production database whose tables pre-date migration history,
-- see README.md for optional `supabase migration repair` commands.
-- =============================================================================
