-- =============================================================================
-- FVMLTD Farmer Crop Assistant — schema reference
-- =============================================================================
-- Source of truth: supabase/migrations/*.sql
--
-- Canonical production tables:
--   farmer_profiles, farms, crop_checks, crop_photos, chat_messages,
--   assessment_results, staff_profiles
--
-- Application extensions (created by the baseline migration when missing):
--   crop_cycles, soil_tests, follow_ups, lab_test_requests, products,
--   recommendations
--
-- Do NOT create parallel tables such as farmers / crop_cases / case_photos /
-- ai_assessments / case_messages / staff_users.
--
-- Apply migrations in filename order (or `supabase db push`).
-- On an existing production database whose tables pre-date migration history,
-- see README.md for optional `supabase migration repair` commands.
-- =============================================================================
